### PR TITLE
Added reference to attributes from parent module in CPython

### PR DESCRIPTION
**Pull request by aziascreations**
This just a simple patch to add references to the implementation's hashlib attributes if it exists.

This omission caused the "*adafruit_rsa*" library to return the following error on CPython, but not on CircuitPython:
```
<redacted>
File "<redacted>\adafruit_rsa\__init__.py", line 17, in <module>
    from adafruit_rsa.pkcs1 import (
File "<redacted>\adafruit_rsa\pkcs1.py", line 37, in <module>
    "MD5": hashlib.md5,
AttributeError: module 'adafruit_hashlib' has no attribute 'md5'
```

More checks can be added if needed in order to reference the library's implementation of the hashing algorithms if they are not present in the implementation's version of *hashlib*.

### CODE REVIEW

**Comment by brentru** [comment]
Hi @aziascreations  - this patch is failing on our build CI, specifically on the PyLint step: https://github.com/adafruit/Adafruit_CircuitPython_hashlib/pull/14/checks?check_run_id=2399955531

Please read thru https://learn.adafruit.com/improve-your-code-with-pylint and make the required changes. If you have any questions about this process, please let me know.

**Comment by jposada202020** [comment]
@aziascreations Hello, would you able to check the links that brentru gave you, let me know if you need any help, we could help you with the PR. Thanks

**Comment by FoamyGuy** [comment]
I re-created the error reported and confirmed the fix.

I've added a commit to import the algos instead of declaring variables which avoids the `invalid-name` issue.

@brentru what do you think of latest version in this PR?

**Review by FoamyGuy — APPROVED** [review]
This fix looks good to me. Tested successfully with CPython

**Pull request merged**
