### PR TITLE
Implement MD5 hash algorithm

### PR DESCRIPTION
**Pull request by timhawes**

### CODE REVIEW

**Comment by brentru** [comment]
@timhawes  Could you please paste the REPL output after running `examples/hashlib_simpletest.py` so I can validate against the CPython MD5 algorithm?

**Comment by timhawes** [comment]
```
Adafruit CircuitPython 7.0.0 on 2021-09-20; FeatherS2 with ESP32S2
>>> import hashlib_simpletest
--MD5--
Msg Digest: 6a61334a5d9f848bea9affcd82864819
Msg Digest Size: 16
Msg Block Size: 64
--SHA1--
Msg Digest: 62c6e222ccd72f21b8ce0c61f42860d6c70954c0
Msg Digest Size: 20
Msg Block Size: 64
--SHA224--
Msg Digest: 744535a10879be6b18bbcdd135032891346f530a7845d580f7869f36
Msg Digest Size: 28
Msg Block Size: 64
--SHA256--
Msg Digest: 3ce8334ca39e66afb9c37d571da4caad68ab4a8bcbd6d584f75e4268e36c0954
Msg Digest Size: 32
Msg Block Size: 64
--SHA384--
Msg Digest: 7a12f0815f5511b8ba52c67922d1ae86dfd9bfcc4e0799ad89a9f01fc526c8f074ddb5948c06db9893536f2e65c7621b
Msg Digest Size: 48
Msg Block Size: 128
--SHA512--
Msg Digest: 20a88a9b04aa490e457f8980e57331bc85c4d6ca30735a9e502f817e74011a9ece07078e53adf70c232ac91f6c79d4cd6cc69426cd77535645fe9016a71122c2
Msg Digest Size: 64
Msg Block Size: 128
>>>
```

**Comment by timhawes** [comment]
I've also passed the following tests on CircuitPython and CPython (with the import line changed as required):

```
from hashlib import md5

# RFC1321 test suite
assert md5(b"").hexdigest() == "d41d8cd98f00b204e9800998ecf8427e"
assert md5(b"a").hexdigest() == "0cc175b9c0f1b6a831c399e269772661"
assert md5(b"abc").hexdigest() == "900150983cd24fb0d6963f7d28e17f72"
assert md5(b"message digest").hexdigest() == "f96b697d7cb7938d525a2f31aaf161d0"
assert md5(b"abcdefghijklmnopqrstuvwxyz").hexdigest() == "c3fcd3d76192e4007dfb496cca67e13b"
assert md5(b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789").hexdigest() == "d174ab98d277d9f5a5611c2c9f419d9f"
assert md5(b"12345678901234567890123456789012345678901234567890123456789012345678901234567890").hexdigest() == "57edf4a22be3c955ac49da2e2107b67a"

# Functional tests
m = md5(b"one")
m.update(b"two")
m.update(b"three")
assert m.digest() == b"{\x03\x91\xfe\xb2\xe0\xcd'\x1f\x1c\xf3\x9a\xaf\xb47o"
assert m.hexdigest() == "7b0391feb2e0cd271f1cf39aafb4376f"
m2 = m.copy()
m.update(b"four")
m2.update(b"five")
assert m.hexdigest() == "645c7d7c377538df94ecd9335cab6bd3"
assert m2.hexdigest() == "f9dc7c7491eb84ed61909eb383800085"

print("ok")
```

**Review by brentru — APPROVED** [review]
LGTM, thanks for providing test results!

**Pull request merged**
